#!/usr/bin/env python3
"""
PR Docs Gate Checker (Walk Level)

Validates that PR documentation exists before merge.
Exit codes: 0=pass, 1=fail, 2=exempt (small PR)

Walk-level checks (blocking):
  1. PR docs folder exists
  2. RESEARCH.md present (>50 bytes)
  3. TEST-STRATEGY.md present (>50 bytes)
  4. IMPLEMENTATION-PLAN.md present (>50 bytes)

Advisory (non-blocking):
  - REVIEW.md exists
  - IMPLEMENTATION.md exists
"""

import sys
import os
from pathlib import Path


def find_pr_folder(pr_num: str) -> Path | None:
    """Find the PR docs folder by PR number."""
    docs_prs = Path("docs/prs")
    search_dirs = [
        docs_prs / "planning",
        docs_prs / "implementing",
        docs_prs / "_archive",
        docs_prs,
    ]

    for search_dir in search_dirs:
        if not search_dir.exists():
            continue
        for folder in search_dir.iterdir():
            if folder.is_dir() and f"PR-{pr_num}" in folder.name:
                return folder
            if folder.is_dir() and f"pr-{pr_num}" in folder.name.lower():
                return folder

    return None


def check_file(folder: Path, filename: str, min_bytes: int = 50) -> tuple[bool, str]:
    """Check if a file exists and has meaningful content."""
    filepath = folder / filename
    if not filepath.exists():
        return False, f"{filename}: MISSING"
    size = filepath.stat().st_size
    if size < min_bytes:
        return False, f"{filename}: TOO SHORT ({size} bytes, need >{min_bytes})"
    return True, f"{filename}: PASS"


def write_summary(pr_num: str, status: str, checks: list[tuple[bool, str]], advisories: list[str] = None):
    """Write the gate summary to /tmp and stdout."""
    lines = [
        f"## PR Docs Gate: {status}",
        f"**PR**: #{pr_num}",
        "",
        "| Check | Status |",
        "|---|---|",
    ]
    for passed, msg in checks:
        icon = "PASS" if passed else "FAIL"
        lines.append(f"| {msg.split(':')[0]} | {icon} |")

    if advisories:
        lines.append("")
        lines.append("### Advisory (non-blocking)")
        for adv in advisories:
            lines.append(f"- {adv}")

    summary = "\n".join(lines)
    Path("/tmp/pr-docs-summary.md").write_text(summary)
    print(summary)


def main():
    if len(sys.argv) < 2:
        print("Usage: pr_docs_check.py <PR_NUMBER>")
        sys.exit(1)

    pr_num = sys.argv[1]

    # Find PR folder
    folder = find_pr_folder(pr_num)
    if not folder:
        write_summary(pr_num, "FAIL", [(False, "PR docs folder: NOT FOUND")])
        sys.exit(1)

    # Blocking checks
    checks = []
    checks.append((True, f"PR docs folder: {folder.name}"))
    checks.append(check_file(folder, "RESEARCH.md"))
    checks.append(check_file(folder, "TEST-STRATEGY.md"))
    checks.append(check_file(folder, "IMPLEMENTATION-PLAN.md"))

    # Advisory checks
    advisories = []
    review_path = folder / "REVIEW.md"
    if not review_path.exists():
        advisories.append("REVIEW.md not found (run /project:review-pr to generate)")
    impl_path = folder / "IMPLEMENTATION.md"
    if not impl_path.exists():
        advisories.append("IMPLEMENTATION.md not found (generated by /project:execute-pr)")

    # Determine pass/fail
    failed = [c for c in checks if not c[0]]
    status = "FAIL" if failed else "PASS"
    write_summary(pr_num, status, checks, advisories if advisories else None)

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
